services:
  # База данных
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: sonzaiigi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Redis для связи C# и Go
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redisdata:/data
    ports:
      - "6379:6379"

volumes:
  pgdata:
  redisdata: